// swift-tools-version: 6.0
// ProjectGoldenEagle core packages. The app target is generated by xcodegen
// (project.yml) and depends on these products; see README.md for pinned commands.
import PackageDescription

let package = Package(
    name: "GoldenEagleKit",
    platforms: [
        .iOS(.v17),
        .macOS(.v14),
    ],
    products: [
        .library(name: "GameCore", targets: ["GameCore"]),
        .library(name: "GameApplication", targets: ["GameApplication"]),
        .library(name: "AppleAdapters", targets: ["AppleAdapters"]),
    ],
    targets: [
        // Authoritative rules and state. Imports nothing — not even Foundation (D-017).
        .target(
            name: "GameCore",
            path: "Sources/GameCore"
        ),
        // Workflows and use cases. Depends inward on GameCore only.
        .target(
            name: "GameApplication",
            dependencies: ["GameCore"],
            path: "Sources/GameApplication"
        ),
        // SwiftUI/SpriteKit/input/audio/persistence/platform integration. Depends inward.
        .target(
            name: "AppleAdapters",
            dependencies: ["GameApplication", "GameCore"],
            path: "Sources/AppleAdapters"
        ),
        .testTarget(
            name: "GameCoreTests",
            dependencies: ["GameCore"],
            path: "Tests/GameCoreTests"
        ),
        .testTarget(
            name: "GameApplicationTests",
            dependencies: ["GameApplication"],
            path: "Tests/GameApplicationTests"
        ),
    ]
)
