#!/bin/sh
# Bundled audio must be exactly what the committed tools produce, and the
# committed manifest must describe exactly those files (R15-09; owner's
# 2026-09-10 creative decision to use excerpts of the reference recording):
#   - synthesized files: regenerated by Tools/build_audio_assets.py into a
#     temporary directory and compared byte for byte, manifest included;
#   - excerpt files (attribution "excerpt"): sha256 against the manifest,
#     the extractor's recorded hash against the committed extractor (an
#     extraction-code change without re-extraction fails even without the
#     source), and — when SPARKTREAD_REFERENCE_WAV is the pinned recording —
#     re-extracted and compared byte for byte INCLUDING every manifest
#     field of each excerpt entry (R25-02).
#   sh Scripts/check-audio.sh            # the check (repository untouched)
#   sh Scripts/check-audio.sh selftest   # corruption/refusal cases on temp copies
set -eu
cd "$(dirname "$0")/.."
bundled="${AUDIO_DIR:-Sources/AppleAdapters/Resources/Audio}"
manifest="${MANIFEST:-Tools/audio_manifest.json}"

field() { python3 -c "import json,sys; print(json.load(open('$manifest'))['files']['$1'].get('$2',''))"; }
names_with() { python3 -c "import json; m=json.load(open('$manifest')); print(' '.join(n for n,e in m['files'].items() if (e.get('attribution')=='excerpt')==$1))"; }

run_check() {
    tmp=$(mktemp -d); trap 'rm -rf "$tmp"' RETURN 2>/dev/null || true
    status=0
    excerpts=$(names_with True)
    synthesized=$(names_with False)

    # 1. Excerpts: file hash against the manifest; extractor hash against the code.
    for name in $excerpts; do
        if [ ! -f "$bundled/$name" ]; then echo "MISSING excerpt $name"; status=1; continue; fi
        want=$(field "$name" sha256); have=$(shasum -a 256 "$bundled/$name" | cut -c1-64)
        [ "$want" = "$have" ] || { echo "EXCERPT DIFFERS from manifest: $name"; status=1; }
    done
    recorded=$(python3 -c "import json; print(json.load(open('$manifest')).get('extractor_sha256',''))")
    actual=$(shasum -a 256 Tools/extract_reference_audio.py | cut -c1-64)
    [ "$recorded" = "$actual" ] || { echo "EXTRACTOR CHANGED without re-extraction (manifest extractor_sha256 stale)"; status=1; }

    # 2. Synthesized: regenerate against a copy of the manifest; compare files and manifest.
    cp "$manifest" "$tmp/manifest.json"
    if ! SPARKTREAD_AUDIO_OUT="$tmp/audio" SPARKTREAD_AUDIO_MANIFEST="$tmp/manifest.json" \
        python3 Tools/build_audio_assets.py > "$tmp/build.log" 2>&1; then
        echo "generator failed: $(tail -1 "$tmp/build.log")"; status=1
    else
        for name in $synthesized; do
            if [ ! -f "$tmp/audio/$name" ]; then echo "generator did not produce $name"; status=1; continue; fi
            if [ ! -f "$bundled/$name" ]; then echo "MISSING bundled $name"; status=1; continue; fi
            cmp -s "$tmp/audio/$name" "$bundled/$name" || { echo "DIFFERS from generator: $name"; status=1; }
        done
        for f in "$tmp"/audio/*.wav; do
            name=$(basename "$f")
            case " $synthesized " in *" $name "*) ;; *) echo "generator produced an unlisted file: $name"; status=1;; esac
        done
        cmp -s "$tmp/manifest.json" "$manifest" || {
            echo "$manifest does not match the generator output; regenerate with python3 Tools/build_audio_assets.py"
            diff "$tmp/manifest.json" "$manifest" | head -20 || true; status=1; }
    fi
    for f in "$bundled"/*.wav; do
        name=$(basename "$f")
        case " $synthesized $excerpts " in *" $name "*) ;; *) echo "STALE bundled file not in the manifest: $name"; status=1;; esac
    done

    # 3. Excerpts re-extracted when the pinned source is at hand: bytes AND
    #    every manifest field of every excerpt entry.
    if [ -n "${SPARKTREAD_REFERENCE_WAV:-}" ] && [ -f "${SPARKTREAD_REFERENCE_WAV}" ]; then
        cp "$manifest" "$tmp/manifest2.json"
        if SPARKTREAD_AUDIO_OUT="$tmp/orig" SPARKTREAD_AUDIO_MANIFEST="$tmp/manifest2.json" \
            python3 Tools/extract_reference_audio.py > "$tmp/extract.log" 2>&1; then
            for name in $excerpts; do
                cmp -s "$tmp/orig/$name" "$bundled/$name" || { echo "EXCERPT DIFFERS from re-extraction: $name"; status=1; }
            done
            python3 - "$manifest" "$tmp/manifest2.json" <<'PY' || status=1
import json, sys
a, b = (json.load(open(p)) for p in sys.argv[1:3])
bad = 0
for name, entry in b["files"].items():
    if entry.get("attribution") != "excerpt": continue
    if a["files"].get(name) != entry:
        print(f"EXCERPT METADATA DIFFERS from re-extraction: {name}"); bad = 1
for key in ("extractor", "extractor_sha256", "rights_review"):
    if a.get(key) != b.get(key):
        print(f"MANIFEST FIELD DIFFERS from re-extraction: {key}"); bad = 1
sys.exit(bad)
PY
            echo "Audio check: excerpts re-extracted from the pinned source; bytes and metadata compared."
        else
            echo "Audio check: re-extraction failed: $(tail -1 "$tmp/extract.log")"; status=1
        fi
    else
        echo "Audio check: excerpts verified by hash and extractor hash only (set SPARKTREAD_REFERENCE_WAV to re-extract)."
    fi
    rm -rf "$tmp"
    [ "$status" -eq 0 ] && echo "Audio check passed: $(echo $synthesized | wc -w | tr -d ' ') synthesized files match the generator, $(echo $excerpts | wc -w | tr -d ' ') excerpts match the manifest."
    return $status
}

selftest() {
    work=$(mktemp -d); trap 'rm -rf "$work"' EXIT
    status=0
    setup() { rm -rf "$work/audio" "$work/manifest.json"; cp -R "Sources/AppleAdapters/Resources/Audio" "$work/audio"; cp Tools/audio_manifest.json "$work/manifest.json"; }
    edit() { python3 - "$work/manifest.json" "$@" <<'PY'
import json, sys
path, name, key, value = sys.argv[1:5]
m = json.load(open(path))
target = m if name == "-" else m["files"][name]
target[key] = json.loads(value) if value.startswith(("[", "{", '"')) else value
json.dump(m, open(path, "w"), indent=2, sort_keys=True); open(path, "a").write("\n")
PY
    }
    expect() { # description, expected exit (0/1)
        if AUDIO_DIR="$work/audio" MANIFEST="$work/manifest.json" sh -c '. "$0" _lib; run_check' "$0" > "$work/log" 2>&1; then got=0; else got=1; fi
        if [ "$got" -eq "$2" ]; then echo "selftest: $1 → $( [ $2 -eq 0 ] && echo passes || echo fails ) as expected"
        else echo "selftest: FAILED — $1 (exit $got, expected $2): $(grep -v '^$' "$work/log" | tail -2)"; status=1; fi
    }
    # The mutated excerpt must BE an excerpt (R27-01): the card became a
    # generated jingle, so the cases target the results passage and assert
    # its attribution first; generated entries get their own case.
    excerpt=sfx_stage_win.wav; generated=sfx_stage_card.wav
    attribution=$(python3 -c "import json; print(json.load(open('Tools/audio_manifest.json'))['files']['$excerpt']['attribution'])")
    [ "$attribution" = "excerpt" ] || { echo "selftest: FAILED — $excerpt is not an excerpt ($attribution)"; return 1; }
    attribution=$(python3 -c "import json; print(json.load(open('Tools/audio_manifest.json'))['files']['$generated']['attribution'])")
    [ "$attribution" != "excerpt" ] || { echo "selftest: FAILED — $generated is an excerpt"; return 1; }
    setup; expect "untouched copy" 0
    setup; edit "$excerpt" sha256 0000000000000000000000000000000000000000000000000000000000000000; expect "excerpt hash corrupted ($excerpt)" 1
    setup; edit - extractor_sha256 0000000000000000000000000000000000000000000000000000000000000000; expect "extractor hash stale" 1
    setup; cp "$work/audio/sfx_dry_fire.wav" "$work/audio/$excerpt"; expect "excerpt bytes replaced ($excerpt)" 1
    setup; edit "$generated" sha256 0000000000000000000000000000000000000000000000000000000000000000; expect "generated entry hash corrupted ($generated)" 1
    setup; cp "$work/audio/sfx_dry_fire.wav" "$work/audio/$generated"; expect "generated file bytes replaced ($generated)" 1
    if [ -n "${SPARKTREAD_REFERENCE_WAV:-}" ] && [ -f "${SPARKTREAD_REFERENCE_WAV}" ]; then
        setup; edit "$excerpt" window_seconds "[0, 1]"; expect "excerpt window corrupted (source-backed, $excerpt)" 1
        setup; edit "$excerpt" source_sha256 "\"deadbeef\""; expect "excerpt source hash corrupted (source-backed, $excerpt)" 1
        setup; edit "$excerpt" processing "\"wrong\""; expect "excerpt processing corrupted (source-backed, $excerpt)" 1
    else
        echo "selftest: source-backed metadata cases skipped (set SPARKTREAD_REFERENCE_WAV)"
    fi
    # Builder refusal must leave a protected file's bytes untouched (R25-03).
    setup; edit sfx_dry_fire.wav attribution "\"excerpt\""
    before=$(shasum -a 256 "$work/audio/sfx_dry_fire.wav" | cut -c1-64)
    if SPARKTREAD_AUDIO_OUT="$work/audio" SPARKTREAD_AUDIO_MANIFEST="$work/manifest.json" python3 Tools/build_audio_assets.py > "$work/build.log" 2>&1; then
        echo "selftest: FAILED — generator accepted a protected name"; status=1
    else
        after=$(shasum -a 256 "$work/audio/sfx_dry_fire.wav" | cut -c1-64)
        [ "$before" = "$after" ] && echo "selftest: generator refuses a protected name and leaves its bytes untouched" \
            || { echo "selftest: FAILED — protected file was overwritten before the refusal"; status=1; }
    fi
    [ $status -eq 0 ] && echo "selftest: passed"
    return $status
}

case "${1:-}" in
    _lib) ;;
    selftest) selftest; exit $? ;;
    *) run_check; exit $? ;;
esac
